using System.Collections.Generic;

namespace StredoEvropskaFilmovaDatabaze.Services;

public class Prekladac
{
    private readonly Dictionary<string, Dictionary<string, string>> slovnik = new()
    {
        ["CZ"] = new()
        {
            ["NadpisHlavniMenu"] = "Středo-evropská filmová databáze",
            ["HlasitostHudba"] = "Hlasitost hudby",
            ["VyberJazyku"] = "Výběr jazyků rozhraní",
            ["TlacitkoZpet"] = "Zpět",
            ["TlacitkoKonec"] = "Konec",
            ["TlacitkoNastaveni"] =  "Nastaveni",
            ["VyhledatFilm"] = "Vyhledat film...",
            ["VyberObrazek"] = "Vyber obrázek",
            ["PopisFilmu"] = "Popis filmu...",
            ["NazevFilmu"] =  "Název filmu...",
            ["RokyVydani"] = "Rok vydání filmu",
            ["ZanrFilmu"] = "Žánr filmu",
            ["DelkaFilmu"] = "Délka filmu: ",
            ["Hodnoceni"] = "Hodnocení...",
            ["Videl"] = "Viděl?",
            ["PridatFilm"] = "Přidat film",
            ["Filtrovat"] = "Filtrovat",
            ["Odstranit"] = "Odstranit",
            ["NazevVyhruzka"] = "|Název nesmí bý prázdný!!!|",
            ["Filtrovat"] = "Filtrovat",
        },
        ["PL"] = new()
        {
            ["NadpisHlavniMenu"] = "Środkowoeuropejska baza filmowa",
            ["HlasitostHudba"] = "Głośność muzyki",
            ["VyberJazyku"] = "Wybór języków interfejsu",
            ["TlacitkoZpet"] = "Wstecz",
            ["TlacitkoKonec"] = "Koniec",
            ["TlacitkoNastaveni"] = "Ustawienia",
            ["VyhledatFilm"] = "Wyszukaj film...",
            ["VyberObrazek"] = "Wybierz obraz",
            ["PopisFilmu"] = "Opis filmu...",
            ["NazevFilmu"] = "Tytuł filmu...",
            ["RokyVydani"] = "Rok wydania filmu",
            ["ZanrFilmu"] = "Gatunek filmu",
            ["DelkaFilmu"] = "Długość filmu: ",
            ["Hodnoceni"] = "Ocena...",
            ["Videl"] = "Obejrzane?",
            ["PridatFilm"] = "Dodaj film",
            ["Filtrovat"] = "Filtruj",
            ["Odstranit"] = "Usuń",
            ["NazevVyhruzka"] = "|Nazwa nie może być pusta!!!|",
        },
        ["SK"] = new()
        {
            ["NadpisHlavniMenu"] = "Stredo-európska filmová databáza",
            ["HlasitostHudba"] = "Hlasitosť hudby",
            ["VyberJazyku"] = "Výber jazykov rozhrania",
            ["TlacitkoZpet"] = "Späť",
            ["TlacitkoKonec"] = "Koniec",
            ["TlacitkoNastaveni"] = "Nastavenia",
            ["VyhledatFilm"] = "Vyhľadať film...",
            ["VyberObrazek"] = "Vyber obrázok",
            ["PopisFilmu"] = "Popis filmu...",
            ["NazevFilmu"] = "Názov filmu...",
            ["RokyVydani"] = "Rok vydania filmu",
            ["ZanrFilmu"] = "Žáner filmu",
            ["DelkaFilmu"] = "Dĺžka filmu: ",
            ["Hodnoceni"] = "Hodnotenie...",
            ["Videl"] = "Videl?",
            ["PridatFilm"] = "Pridať film",
            ["Filtrovat"] = "Filtrovať",
            ["Odstranit"] = "Odstrániť",
            ["NazevVyhruzka"] = "|Názov nesmie byť prázdny!!!|",
        },
        ["DE"] = new()
        {
            ["NadpisHlavniMenu"] = "Mitteleuropäische Filmdatenbank",
            ["HlasitostHudba"] = "Musiklautstärke",
            ["VyberJazyku"] = "Auswahl der Schnittstellensprachen",
            ["TlacitkoZpet"] = "Zurück",
            ["TlacitkoKonec"] = "Beenden",
            ["TlacitkoNastaveni"] = "Einstellungen",
            ["VyhledatFilm"] = "Film suchen...",
            ["VyberObrazek"] = "Bild auswählen",
            ["PopisFilmu"] = "Filmbeschreibung...",
            ["NazevFilmu"] = "Filmtitel...",
            ["RokyVydani"] = "Erscheinungsjahr des Films",
            ["ZanrFilmu"] = "Filmgenre",
            ["DelkaFilmu"] = "Filmlänge: ",
            ["Hodnoceni"] = "Bewertung...",
            ["Videl"] = "Gesehen?",
            ["PridatFilm"] = "Film hinzufügen",
            ["Filtrovat"] = "Filtern",
            ["Odstranit"] = "Entfernen",
            ["NazevVyhruzka"] = "|Titel darf nicht leer sein!!!|",
        },
        ["MGR"] = new()
        {
            ["NadpisHlavniMenu"] = "Közép-európai filmadatbázis",
            ["HlasitostHudba"] = "Zene hangereje",
            ["VyberJazyku"] = "Felület nyelveinek kiválasztása",
            ["TlacitkoZpet"] = "Vissza",
            ["TlacitkoKonec"] = "Kilépés",
            ["TlacitkoNastaveni"] = "Beállítások",
            ["VyhledatFilm"] = "Film keresése...",
            ["VyberObrazek"] = "Kép kiválasztása",
            ["PopisFilmu"] = "Film leírása...",
            ["NazevFilmu"] = "Film címe...",
            ["RokyVydani"] = "Film kiadási éve",
            ["ZanrFilmu"] = "Film műfaja",
            ["DelkaFilmu"] = "Film hossza: ",
            ["Hodnoceni"] = "Értékelés...",
            ["Videl"] = "Megnézted?",
            ["PridatFilm"] = "Film hozzáadása",
            ["Filtrovat"] = "Szűrés",
            ["Odstranit"] = "Eltávolítás",
            ["NazevVyhruzka"] = "|A cím nem lehet üres!!!|",
        },
        ["CHO"] = new()
        {
            ["NadpisHlavniMenu"] = "Srednjoeuropska filmska baza podataka",
            ["HlasitostHudba"] = "Glasnoća glazbe",
            ["VyberJazyku"] = "Odabir jezika sučelja",
            ["TlacitkoZpet"] = "Natrag",
            ["TlacitkoKonec"] = "Kraj",
            ["TlacitkoNastaveni"] = "Postavke",
            ["VyhledatFilm"] = "Pretraži film...",
            ["VyberObrazek"] = "Odaberi sliku",
            ["PopisFilmu"] = "Opis filma...",
            ["NazevFilmu"] = "Naziv filma...",
            ["RokyVydani"] = "Godina izdanja filma",
            ["ZanrFilmu"] = "Žanr filma",
            ["DelkaFilmu"] = "Trajanje filma: ",
            ["Hodnoceni"] = "Ocjena...",
            ["Videl"] = "Vidio?",
            ["PridatFilm"] = "Dodaj film",
            ["Filtrovat"] = "Filtriraj",
            ["Odstranit"] = "Ukloni",
            ["NazevVyhruzka"] = "|Naziv ne smije biti prazan!!!|",
        },
        ["UKR"] = new()
        {
            ["NadpisHlavniMenu"] = "Середньоєвропейська фільмова база даних",
            ["HlasitostHudba"] = "Гучність музики",
            ["VyberJazyku"] = "Вибір мов інтерфейсу",
            ["TlacitkoZpet"] = "Назад",
            ["TlacitkoKonec"] = "Вихід",
            ["TlacitkoNastaveni"] = "Налаштування",
            ["VyhledatFilm"] = "Знайти фільм...",
            ["VyberObrazek"] = "Вибери зображення",
            ["PopisFilmu"] = "Опис фільму...",
            ["NazevFilmu"] = "Назва фільму...",
            ["RokyVydani"] = "Рік випуску фільму",
            ["ZanrFilmu"] = "Жанр фільму",
            ["DelkaFilmu"] = "Тривалість фільму: ",
            ["Hodnoceni"] = "Оцінка...",
            ["Videl"] = "Переглянув?",
            ["PridatFilm"] = "Додати фільм",
            ["Filtrovat"] = "Фільтрувати",
            ["Odstranit"] = "Видалити",
            ["NazevVyhruzka"] = "|Назва не може бути порожньою!!!|",
        },
        ["RO"] = new()
        {
            ["NadpisHlavniMenu"] = "Baza de date cinematografică central-europeană",
            ["HlasitostHudba"] = "Volum muzică",
            ["VyberJazyku"] = "Selectarea limbilor interfeței",
            ["TlacitkoZpet"] = "Înapoi",
            ["TlacitkoKonec"] = "Ieșire",
            ["TlacitkoNastaveni"] = "Setări",
            ["VyhledatFilm"] = "Caută film...",
            ["VyberObrazek"] = "Selectează imaginea",
            ["PopisFilmu"] = "Descrierea filmului...",
            ["NazevFilmu"] = "Titlul filmului...",
            ["RokyVydani"] = "Anul lansării filmului",
            ["ZanrFilmu"] = "Genul filmului",
            ["DelkaFilmu"] = "Durata filmului: ",
            ["Hodnoceni"] = "Evaluare...",
            ["Videl"] = "Văzut?",
            ["PridatFilm"] = "Adaugă film",
            ["Filtrovat"] = "Filtrează",
            ["Odstranit"] = "Elimină",
            ["NazevVyhruzka"] = "|Titlul nu poate fi gol!!!|",
        },
        ["BUL"] = new()
        {
            ["NadpisHlavniMenu"] = "Средноевропейска филмова база данни",
            ["HlasitostHudba"] = "Сила на звука на музиката",
            ["VyberJazyku"] = "Избор на езици на интерфейса",
            ["TlacitkoZpet"] = "Назад",
            ["TlacitkoKonec"] = "Край",
            ["TlacitkoNastaveni"] = "Настройки",
            ["VyhledatFilm"] = "Търсене на филм...",
            ["VyberObrazek"] = "Избери изображение",
            ["PopisFilmu"] = "Описание на филма...",
            ["NazevFilmu"] = "Заглавие на филма...",
            ["RokyVydani"] = "Година на издаване на филма",
            ["ZanrFilmu"] = "Жанр на филма",
            ["DelkaFilmu"] = "Продължителност на филма: ",
            ["Hodnoceni"] = "Оценка...",
            ["Videl"] = "Гледал?",
            ["PridatFilm"] = "Добави филм",
            ["Filtrovat"] = "Филтрирай",
            ["Odstranit"] = "Премахни",
            ["NazevVyhruzka"] = "|Заглавието не може да бъде празно!!!|",
        },
        ["GR"] = new()
        {
            ["NadpisHlavniMenu"] = "Κεντροευρωπαϊκή κινηματογραφική βάση δεδομένων",
            ["HlasitostHudba"] = "Ένταση μουσικής",
            ["VyberJazyku"] = "Επιλογή γλωσσών διεπαφής",
            ["TlacitkoZpet"] = "Πίσω",
            ["TlacitkoKonec"] = "Τέλος",
            ["TlacitkoNastaveni"] = "Ρυθμίσεις",
            ["VyhledatFilm"] = "Αναζήτηση ταινίας...",
            ["VyberObrazek"] = "Επιλογή εικόνας",
            ["PopisFilmu"] = "Περιγραφή ταινίας...",
            ["NazevFilmu"] = "Τίτλος ταινίας...",
            ["RokyVydani"] = "Έτος κυκλοφορίας ταινίας",
            ["ZanrFilmu"] = "Είδος ταινίας",
            ["DelkaFilmu"] = "Διάρκεια ταινίας: ",
            ["Hodnoceni"] = "Βαθμολογία...",
            ["Videl"] = "Το είδες;",
            ["PridatFilm"] = "Προσθήκη ταινίας",
            ["Filtrovat"] = "Φιλτράρισμα",
            ["Odstranit"] = "Διαγραφή",
            ["NazevVyhruzka"] = "|Ο τίτλος δεν μπορεί να είναι κενός!!!|",
        },
        ["SRB"] = new()
        {
            ["NadpisHlavniMenu"] = "Средњоевропска филмска база података",
            ["HlasitostHudba"] = "Jačina zvuka muzike",
            ["VyberJazyku"] = "Izbor jezika interfejsa",
            ["TlacitkoZpet"] = "Nazad",
            ["TlacitkoKonec"] = "Kraj",
            ["TlacitkoNastaveni"] = "Podešavanja",
            ["VyhledatFilm"] = "Pretraži film...",
            ["VyberObrazek"] = "Izaberi sliku",
            ["PopisFilmu"] = "Opis filma...",
            ["NazevFilmu"] = "Naziv filma...",
            ["RokyVydani"] = "Godina izdanja filma",
            ["ZanrFilmu"] = "Žanr filma",
            ["DelkaFilmu"] = "Dužina filma: ",
            ["Hodnoceni"] = "Ocena...",
            ["Videl"] = "Video?",
            ["PridatFilm"] = "Dodaj film",
            ["Filtrovat"] = "Filtriraj",
            ["Odstranit"] = "Ukloni",
            ["NazevVyhruzka"] = "|Naziv ne sme biti prazan!!!|",
            
        },
        ["LT"] = new()
        {
            ["NadpisHlavniMenu"] = "Vidurio Europos filmų duomenų bazė",
            ["HlasitostHudba"] = "Muzikos garsumas",
            ["VyberJazyku"] = "Sąsajos kalbų pasirinkimas",
            ["TlacitkoZpet"] = "Atgal",
            ["TlacitkoKonec"] = "Baigti",
            ["TlacitkoNastaveni"] = "Nustatymai",
            ["VyhledatFilm"] = "Ieškoti filmo...",
            ["VyberObrazek"] = "Pasirinkti paveikslėlį",
            ["PopisFilmu"] = "Filmo aprašymas...",
            ["NazevFilmu"] = "Filmo pavadinimas...",
            ["RokyVydani"] = "Filmo išleidimo metai",
            ["ZanrFilmu"] = "Filmo žanras",
            ["DelkaFilmu"] = "Filmo trukmė: ",
            ["Hodnoceni"] = "Įvertinimas...",
            ["Videl"] = "Matėte?",
            ["PridatFilm"] = "Pridėti filmą",
            ["Filtrovat"] = "Filtruoti",
            ["Odstranit"] = "Pašalinti",
            ["NazevVyhruzka"] = "|Pavadinimas negali būti tuščias!!!|",
        },
        ["IT"] = new()
        {
            ["NadpisHlavniMenu"] = "Database cinematografico dell'Europa centrale",
            ["HlasitostHudba"] = "Volume della musica",
            ["VyberJazyku"] = "Selezione delle lingue dell'interfaccia",
            ["TlacitkoZpet"] = "Indietro",
            ["TlacitkoKonec"] = "Esci",
            ["TlacitkoNastaveni"] = "Impostazioni",
            ["VyhledatFilm"] = "Cerca film...",
            ["VyberObrazek"] = "Seleziona immagine",
            ["PopisFilmu"] = "Descrizione del film...",
            ["NazevFilmu"] = "Titolo del film...",
            ["RokyVydani"] = "Anno di uscita del film",
            ["ZanrFilmu"] = "Genere del film",
            ["DelkaFilmu"] = "Durata del film: ",
            ["Hodnoceni"] = "Valutazione...",
            ["Videl"] = "Visto?",
            ["PridatFilm"] = "Aggiungi film",
            ["Filtrovat"] = "Filtra",
            ["Odstranit"] = "Rimuovi",
            ["NazevVyhruzka"] = "|Il titolo non può essere vuoto!!!|",
        },
        ["BEL"] = new()
        {
            ["NadpisHlavniMenu"] = "Сярэднееўрапейская фільмавая база даных",
            ["HlasitostHudba"] = "Гучнасць музыкі",
            ["VyberJazyku"] = "Выбар моў інтэрфейсу",
            ["TlacitkoZpet"] = "Назад",
            ["TlacitkoKonec"] = "Выхад",
            ["TlacitkoNastaveni"] = "Налады",
            ["VyhledatFilm"] = "Пошук фільма...",
            ["VyberObrazek"] = "Выберы выява",
            ["PopisFilmu"] = "Апісанне фільма...",
            ["NazevFilmu"] = "Назва фільма...",
            ["RokyVydani"] = "Год выхаду фільма",
            ["ZanrFilmu"] = "Жанр фільма",
            ["DelkaFilmu"] = "Працягласць фільма: ",
            ["Hodnoceni"] = "Ацэнка...",
            ["Videl"] = "Бачыў?",
            ["PridatFilm"] = "Дадаць фільм",
            ["Filtrovat"] = "Фільтраваць",
            ["Odstranit"] = "Выдаліць",
            ["NazevVyhruzka"] = "|Назва не можа быць пустой!!!|",
        },
        ["BOS"] = new()
        {
            ["NadpisHlavniMenu"] = "Srednjoevropska filmska baza podataka",
            ["HlasitostHudba"] = "Glasnoća muzike",
            ["VyberJazyku"] = "Odabir jezika interfejsa",
            ["TlacitkoZpet"] = "Nazad",
            ["TlacitkoKonec"] = "Kraj",
            ["TlacitkoNastaveni"] = "Postavke",
            ["VyhledatFilm"] = "Pretraži film...",
            ["VyberObrazek"] = "Odaberi sliku",
            ["PopisFilmu"] = "Opis filma...",
            ["NazevFilmu"] = "Naziv filma...",
            ["RokyVydani"] = "Godina izdanja filma",
            ["ZanrFilmu"] = "Žanr filma",
            ["DelkaFilmu"] = "Dužina filma: ",
            ["Hodnoceni"] = "Ocjena...",
            ["Videl"] = "Vidio?",
            ["PridatFilm"] = "Dodaj film",
            ["Filtrovat"] = "Filtriraj",
            ["Odstranit"] = "Ukloni",
            ["NazevVyhruzka"] = "|Naziv ne smije biti prazan!!!|",
            
        },
        ["AL"] = new()
        {
            ["NadpisHlavniMenu"] = "Baza e të dhënave filmike të Evropës Qendrore",
            ["HlasitostHudba"] = "Volumi i muzikës",
            ["VyberJazyku"] = "Zgjedhja e gjuhëve të ndërfaqes",
            ["TlacitkoZpet"] = "Kthehu",
            ["TlacitkoKonec"] = "Dalje",
            ["TlacitkoNastaveni"] = "Cilësimet",
            ["VyhledatFilm"] = "Kërko film...",
            ["VyberObrazek"] = "Zgjidh imazhin",
            ["PopisFilmu"] = "Përshkrimi i filmit...",
            ["NazevFilmu"] = "Titulli i filmit...",
            ["RokyVydani"] = "Viti i daljes së filmit",
            ["ZanrFilmu"] = "Zhanri i filmit",
            ["DelkaFilmu"] = "Gjatësia e filmit: ",
            ["Hodnoceni"] = "Vlerësimi...",
            ["Videl"] = "E pa?",
            ["PridatFilm"] = "Shto film",
            ["Filtrovat"] = "Filtro",
            ["Odstranit"] = "Hiq",
            ["NazevVyhruzka"] = "|Titulli nuk mund të jetë bosh!!!|",
        },
    };
    
    public string this[string klic] => slovnik[Settings.Instance.Jazyk][klic];
    public Prekladac T => this;
}